FROM ghcr.io/linuxserver/baseimage-ubuntu:jammy AS builder
ARG DEBIAN_FRONTEND="noninteractive"
ARG PYTHONNUM='3.11' PYTHONVERALL="3.11.7"
ARG PYTHONVER="python-${PYTHONVERALL}" PYTHONFILENAME="Python-${PYTHONVERALL}"
ENV LANG C.UTF-8
# 安装依赖和编译工具
RUN apt-get update && \
  apt-get install -y build-essential curl libffi-dev libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev \
  llvm libncurses5-dev xz-utils tk-dev liblzma-dev libffi-dev  make  wget  libncursesw5-dev openssl zlib1g \
  xz-utils tk-dev libffi-dev liblzma-dev libkrb5-dev
RUN echo "https://www.python.org/ftp/python/${PYTHONVERALL}/${PYTHONFILENAME}.tgz" &&sleep 5 && \
  rm -rf /var/lib/apt/lists/* && cd / && curl -LO "https://www.python.org/ftp/python/${PYTHONVERALL}/${PYTHONFILENAME}.tgz" && \
  tar xf "${PYTHONFILENAME}.tgz" && cd /${PYTHONFILENAME} && \
  ./configure --prefix=/usr/local/${PYTHONVER} --enable-optimizations --enable-shared && \
  make -j $(nproc) && \
  make altinstall && cd / && rm -rf /${PYTHONFILENAME} /${PYTHONFILENAME}.tgz

# 第二阶段，构建 Python 应用镜像
FROM ghcr.io/linuxserver/baseimage-ubuntu:jammy
ARG DEBIAN_FRONTEND="noninteractive"
# set version label
ARG BUILD_DATE VERSION CODE_RELEASE PYTHONNUM='3.11' PYTHONVERALL="3.11.7"
ARG GOVERS="1.22.3" NODE_VERSION="v22.2.0" NODE_DISTRO="linux-x64" CONDA_SCRIPT="Miniconda3-latest-Linux-x86_64.sh" CONDA_PATH="/usr/local/miniconda3"
ARG PYTHONVER="python-${PYTHONVERALL}" PYTHONFILENAME="Python-${PYTHONVERALL}"  PYLIBS="/config/pylibs/python${PYTHONVERALL}"
ARG GOFILE="go${GOVERS}.linux-amd64.tar.gz" NODEFILE="node-${NODE_VERSION}-${NODE_DISTRO}.tar.xz" 
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="aptalca"
ENV HOME="/config" GOPATH="/config/gopath" GOPROXY="https://goproxy.cn,direct"
# ENV PYTHONPATH="/usr/local/${PYTHONVER}/lib/python${PYTHONNUM}/site-packages:${PYLIBS}/site-packages"
# 拷贝 Python 环境
COPY --from=builder /usr/local/${PYTHONVER} /usr/local/${PYTHONVER}
# 更新 apt 并安装应用所需依赖
RUN echo 'abc:Test12#$' |chpasswd && echo 'root:Test12#$' |chpasswd && \
  apt-get update && \
  apt-get install -y libreadline8  libncursesw6 liblzma5 build-essential \
  procps  subversion inetutils-ping telnet openssl libssl-dev libsecret-1-0 libncurses5-dev libncursesw5-dev \
  curl libbz2-dev libreadline-dev llvm xz-utils tk-dev liblzma-dev libffi-dev libgdbm-dev libgdbm-compat-dev \
  debian-keyring debian-archive-keyring apt-transport-https openssh-client maven krb5-config \
  vim bash-completion groff less unzip rsync \
  openjdk-18-jdk-headless \
  git jq libatomic1 net-tools netcat sudo amazon-ecr-credential-helper \
  pgloader zip \
  --no-install-recommends && \
  mkdir /config/gopath /usr/local/go /usr/local/lib/nodejs && \
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' |gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg &&\
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list && \
  apt-get update && apt-get install -y caddy && \
  apt-get remove -y debian-keyring debian-archive-keyring apt-transport-https && \
  sed -i '/root.*ALL/aabc ALL=(ALL:ALL) NOPASSWD: ALL' /etc/sudoers && \
  echo "**** install code-server ****" && \
  if [ -z ${CODE_RELEASE+x} ]; then \
  CODE_RELEASE=$(curl -sX GET https://api.github.com/repos/coder/code-server/releases/latest \
  | awk '/tag_name/{print $4;exit}' FS='[""]' | sed 's|^v||'); \
  fi && \
  mkdir -p /app/code-server && \
  curl -o \
  /tmp/code-server.tar.gz -L \
  "https://github.com/coder/code-server/releases/download/v${CODE_RELEASE}/code-server-${CODE_RELEASE}-linux-amd64.tar.gz" && \
  tar xf /tmp/code-server.tar.gz -C \
  /app/code-server --strip-components=1 && \
  cd /tmp && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip && \
  cd /tmp && unzip awscliv2.zip  && rm -f awscliv2.zip && ./aws/install && \
  curl -o /tmp/go.tar.gz -L "https://go.dev/dl/${GOFILE}" && tar xf go.tar.gz -C /usr/local && \
  curl -o /tmp/node.tar.gz -L "https://nodejs.org/dist/${NODE_VERSION}/${NODEFILE}" && tar xf node.tar.gz -C /usr/local/lib/nodejs && \
  curl -o /tmp/miniconda.sh -L "https://repo.anaconda.com/miniconda/${CONDA_SCRIPT}" && \
  bash miniconda.sh -b -u -p ${CONDA_PATH} && \
  echo "**** clean up ****" && \
  apt-get clean && \
  rm -rf \
  /config/* \
  /tmp/* \
  /var/lib/apt/lists/* \
  /var/tmp/* 
COPY requirements.txt /
ADD teop-sdk-python.tar.gz /teop
RUN echo 'HISTSIZE=100000' >> /etc/profile && \
  echo "/usr/local/${PYTHONVER}/lib" >> /etc/ld.so.conf && /sbin/ldconfig -v && \
  echo "export PATH=\"${CONDA_PATH}/bin:/usr/local/${PYTHONVER}/bin:/usr/local/go/bin:\$PATH:/usr/local/lib/nodejs/node-${NODE_VERSION}-${NODE_DISTRO}/bin:${PYLIBS}/site-packages/bin\"" >> /etc/profile && \
  ln -s /usr/local/${PYTHONVER}/bin/pip${PYTHONNUM} /usr/bin/pip3 && ln -s /usr/bin/pip3 /usr/bin/pip && \
  ln -s /usr/local/${PYTHONVER}/bin/python${PYTHONNUM} /usr/bin/python3 && ln -s /usr/bin/python3 /usr/bin/python && \
  cd /teop/teop-sdk-python && python3 setup.py install && pip3 install ansible==5.10.0 ansible-core==2.12.10 ansible-lint==5.4.0  --no-cache-dir && find /usr/local -depth \( \( -type d -a \( -name test -o -name tests -o -name idle_test \) \) -o \( -type f -a \( -name '*.pyc' -o -name '*.pyo' -o -name 'libpython*.a' \) \) \) -exec rm -rf '{}' + ;
RUN ${CONDA_PATH}/bin/conda init bash
COPY openssl.cnf  /etc/ssl/openssl.cnf
COPY /root /

# ports and volumes
EXPOSE 8443
