name: Build and Release Docker Image

on:
  push:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name"
        required: false

jobs:
  build:
    name: Build Binaries and Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          COMMIT_ID=$(echo ${{ github.sha }} | cut -c1-7)
          echo "Building and pushing Docker images with tag $TAG"
          make build-remote-docker COMMIT_ID=$COMMIT_ID
        env:
          DOCKER_BUILDKIT: 1
